apiVersion: v1
kind: Service
metadata:
  name: ncc-v2-api
  namespace: ncc-orchestrator-v2
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: ncc-orchestrator-v2
    component: api
