apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ncc-v2-ui-ingress
  namespace: ncc-orchestrator-v2
spec:
  podSelector:
    matchLabels:
      app: ncc-orchestrator-v2
      component: ui
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 8080
