apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ncc-v2-api-ingress-from-ui
  namespace: ncc-orchestrator-v2
spec:
  podSelector:
    matchLabels:
      app: ncc-orchestrator-v2
      component: api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ncc-orchestrator-v2
              component: ui
      ports:
        - protocol: TCP
          port: 8081
