apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ncc-v2-api
  namespace: ncc-orchestrator-v2
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ncc-orchestrator-v2
      component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ncc-v2-ui
  namespace: ncc-orchestrator-v2
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ncc-orchestrator-v2
      component: ui
