apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ncc-v2-data
  namespace: ncc-orchestrator-v2
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
